### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by ahmadsj94** [jgaeddert/liquid-usrp#8]
lib/multichanneltx.cc: In member function ‘void multichanneltx::UpdateData(unsigned int, unsigned char*, unsigned char*, unsigned int, int, int, int)’:
lib/multichanneltx.cc:184:73: warning: narrowing conversion of ‘_fec0’ from ‘int’ to ‘unsigned int’ inside { } is ill-formed in C++11 [-Wnarrowing]
     ofdmflexframegenprops_s fgprops = {LIQUID_CRC_32, _fec0, _fec1, _mod};
                                                                         ^
lib/multichanneltx.cc:184:73: warning: narrowing conversion of ‘_fec1’ from ‘int’ to ‘unsigned int’ inside { } is ill-formed in C++11 [-Wnarrowing]
lib/multichanneltx.cc:184:73: warning: narrowing conversion of ‘_mod’ from ‘int’ to ‘unsigned int’ inside { } is ill-formed in C++11 [-Wnarrowing]
lib/multichanneltx.cc: In member function ‘void multichanneltx::GenerateFrameSamples()’:
lib/multichanneltx.cc:236:66: error: ‘ofdmflexframegen_writesymbol’ was not declared in this scope
             ofdmflexframegen_writesymbol(framegen[i], fgbuffer[i]);
                                                                  ^
make: *** [lib/multichanneltx.o] Error 1

This is the error I get when trying to make.

**Comment by jgaeddert** [comment]
The interface changed for liquid-dsp 1.3.0 which breaks binary compatibility. I'll look into it.

**Comment by jgaeddert** [comment]
Should work with liquid-dsp 1.3.0 now.
